s/#TSS_Code/Study_Name/g
s/01/Ovarian_serous_cystadenocarcinoma/g
s/02/Glioblastoma_multiforme/g
s/04/Ovarian_serous_cystadenocarcinoma/g
s/05/Lung_adenocarcinoma/g
s/06/Glioblastoma_multiforme/g
s/07/Cell_Line_Control/g
s/08/Glioblastoma_multiforme/g
s/09/Ovarian_serous_cystadenocarcinoma/g
s/10/Ovarian_serous_cystadenocarcinoma/g
s/11/Lung_squamous_cell_carcinoma/g
s/12/Glioblastoma_multiforme/g
s/13/Ovarian_serous_cystadenocarcinoma/g
s/14/Glioblastoma_multiforme/g
s/15/Glioblastoma_multiforme/g
s/16/Glioblastoma_multiforme/g
s/17/Lung_adenocarcinoma/g
s/18/Lung_squamous_cell_carcinoma/g
s/19/Glioblastoma_multiforme/g
s/1Z/Thymoma/g
s/20/Ovarian_serous_cystadenocarcinoma/g
s/21/Lung_squamous_cell_carcinoma/g
s/22/Lung_squamous_cell_carcinoma/g
s/23/Ovarian_serous_cystadenocarcinoma/g
s/24/Ovarian_serous_cystadenocarcinoma/g
s/25/Ovarian_serous_cystadenocarcinoma/g
s/26/Glioblastoma_multiforme/g
s/27/Glioblastoma_multiforme/g
s/28/Glioblastoma_multiforme/g
s/29/Ovarian_serous_cystadenocarcinoma/g
s/2A/Prostate_adenocarcinoma/g
s/2E/Uterine_Corpus_Endometrial_Carcinoma/g
s/2F/Bladder_Urothelial_Carcinoma/g
s/2G/Testicular_Germ_Cell_Tumors/g
s/2H/Esophageal_carcinoma/g
s/2J/Pancreatic_adenocarcinoma/g
s/2K/Kidney_renal_papillary_cell_carcinoma/g
s/2L/Pancreatic_adenocarcinoma/g
s/2M/Esophageal_carcinoma/g
s/2N/Stomach_adenocarcinoma/g
s/2P/Pancreatic_adenocarcinoma/g
s/2V/Liver_hepatocellular_carcinoma/g
s/2W/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/2X/Testicular_Germ_Cell_Tumors/g
s/2Y/Liver_hepatocellular_carcinoma/g
s/2Z/Kidney_renal_papillary_cell_carcinoma/g
s/30/Ovarian_serous_cystadenocarcinoma/g
s/31/Ovarian_serous_cystadenocarcinoma/g
s/32/Glioblastoma_multiforme/g
s/33/Lung_squamous_cell_carcinoma/g
s/34/Lung_squamous_cell_carcinoma/g
s/35/Lung_adenocarcinoma/g
s/36/Ovarian_serous_cystadenocarcinoma/g
s/37/Lung_squamous_cell_carcinoma/g
s/38/Lung_adenocarcinoma/g
s/39/Lung_squamous_cell_carcinoma/g
s/3A/Pancreatic_adenocarcinoma/g
s/3B/Sarcoma/g
s/3C/Breast_invasive_carcinoma/g
s/3E/Pancreatic_adenocarcinoma/g
s/3G/Thymoma/g
s/3H/Mesothelioma/g
s/3J/Breast_invasive_carcinoma/g
s/3K/Liver_hepatocellular_carcinoma/g
s/3L/Colon_adenocarcinoma/g
s/3M/Stomach_adenocarcinoma/g
s/3N/Skin_Cutaneous_Melanoma/g
s/3P/Ovarian_serous_cystadenocarcinoma/g
s/3Q/Thymoma/g
s/3R/Sarcoma/g
s/3S/Thymoma/g
s/3T/Thymoma/g
s/3U/Mesothelioma/g
s/3W/Sarcoma/g
s/3X/Cholangiocarcinoma/g
s/3Z/Kidney_renal_clear_cell_carcinoma/g
s/41/Glioblastoma_multiforme/g
s/42/Ovarian_serous_cystadenocarcinoma/g
s/43/Lung_squamous_cell_carcinoma/g
s/44/Lung_adenocarcinoma/g
s/46/Lung_squamous_cell_carcinoma/g
s/49/Lung_adenocarcinoma/g
s/4A/Kidney_renal_papillary_cell_carcinoma/g
s/4B/Lung_adenocarcinoma/g
s/4C/Thyroid_carcinoma/g
s/4D/Ovarian_serous_cystadenocarcinoma/g
s/4E/Uterine_Corpus_Endometrial_Carcinoma/g
s/4G/Cholangiocarcinoma/g
s/4H/Breast_invasive_carcinoma/g
s/4J/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/4K/Testicular_Germ_Cell_Tumors/g
s/4L/Prostate_adenocarcinoma/g
s/4N/Colon_adenocarcinoma/g
s/4P/Head_and_Neck_squamous_cell_carcinoma/g
s/4Q/Sarcoma/g
s/4R/Liver_hepatocellular_carcinoma/g
s/4S/Prostate_adenocarcinoma/g
s/4T/Colon_adenocarcinoma/g
s/4V/Thymoma/g
s/4W/Glioblastoma_multiforme/g
s/4X/Thymoma/g
s/4Y/Sarcoma/g
s/4Z/Bladder_Urothelial_Carcinoma/g
s/50/Lung_adenocarcinoma/g
s/51/Lung_squamous_cell_carcinoma/g
s/52/Lung_squamous_cell_carcinoma/g
s/53/Lung_adenocarcinoma/g
s/55/Lung_adenocarcinoma/g
s/56/Lung_squamous_cell_carcinoma/g
s/57/Ovarian_serous_cystadenocarcinoma/g
s/58/Lung_squamous_cell_carcinoma/g
s/59/Ovarian_serous_cystadenocarcinoma/g
s/5A/Cholangiocarcinoma/g
s/5B/Uterine_Corpus_Endometrial_Carcinoma/g
s/5C/Liver_hepatocellular_carcinoma/g
s/5D/Sarcoma/g
s/5F/Thyroid_carcinoma/g
s/5G/Thymoma/g
s/5H/Uveal_Melanoma/g
s/5J/Acute_Myeloid_Leukemia/g
s/5K/Thymoma/g
s/5L/Breast_invasive_carcinoma/g
s/5M/Colon_adenocarcinoma/g
s/5N/Bladder_Urothelial_Carcinoma/g
s/5P/Kidney_renal_papillary_cell_carcinoma/g
s/5Q/Pancreatic_adenocarcinoma/g
s/5R/Liver_hepatocellular_carcinoma/g
s/5S/Uterine_Corpus_Endometrial_Carcinoma/g
s/5T/Breast_invasive_carcinoma/g
s/5U/Thymoma/g
s/5V/Thymoma/g
s/5W/Uterine_Corpus_Endometrial_Carcinoma/g
s/5X/Ovarian_serous_cystadenocarcinoma/g
s/60/Lung_squamous_cell_carcinoma/g
s/61/Ovarian_serous_cystadenocarcinoma/g
s/62/Lung_adenocarcinoma/g
s/63/Lung_squamous_cell_carcinoma/g
s/64/Lung_adenocarcinoma/g
s/65/Glioblastoma_multiforme/g
s/66/Lung_squamous_cell_carcinoma/g
s/67/Lung_adenocarcinoma/g
s/68/Lung_squamous_cell_carcinoma/g
s/69/Lung_adenocarcinoma/g
s/6A/Lung_squamous_cell_carcinoma/g
s/6D/Kidney_renal_clear_cell_carcinoma/g
s/6G/Rectum_adenocarcinoma/g
s/6H/Chronic_Myelogenous_Leukemia/g
s/70/Lung_squamous_cell_carcinoma/g
s/71/Lung_adenocarcinoma/g
s/72/Ovarian_serous_cystadenocarcinoma/g
s/73/Lung_adenocarcinoma/g
s/74/Glioblastoma_multiforme/g
s/75/Lung_adenocarcinoma/g
s/76/Glioblastoma_multiforme/g
s/77/Lung_squamous_cell_carcinoma/g
s/78/Lung_adenocarcinoma/g
s/79/Lung_squamous_cell_carcinoma/g
s/80/Lung_adenocarcinoma/g
s/81/Glioblastoma_multiforme/g
s/82/Lung_squamous_cell_carcinoma/g
s/83/Lung_adenocarcinoma/g
s/85/Lung_squamous_cell_carcinoma/g
s/86/Lung_adenocarcinoma/g
s/87/Glioblastoma_multiforme/g
s/90/Lung_squamous_cell_carcinoma/g
s/91/Lung_adenocarcinoma/g
s/92/Lung_squamous_cell_carcinoma/g
s/93/Lung_adenocarcinoma/g
s/94/Lung_squamous_cell_carcinoma/g
s/95/Lung_adenocarcinoma/g
s/96/Lung_squamous_cell_carcinoma/g
s/97/Lung_adenocarcinoma/g
s/98/Lung_squamous_cell_carcinoma/g
s/99/Lung_adenocarcinoma/g
s/A1/Breast_invasive_carcinoma/g
s/A2/Breast_invasive_carcinoma/g
s/A3/Kidney_renal_clear_cell_carcinoma/g
s/A4/Kidney_renal_papillary_cell_carcinoma/g
s/A5/Uterine_Corpus_Endometrial_Carcinoma/g
s/A6/Colon_adenocarcinoma/g
s/A7/Breast_invasive_carcinoma/g
s/A8/Breast_invasive_carcinoma/g
s/AA/Colon_adenocarcinoma/g
s/AB/Acute_Myeloid_Leukemia/g
s/AC/Breast_invasive_carcinoma/g
s/AD/Colon_adenocarcinoma/g
s/AF/Rectum_adenocarcinoma/g
s/AG/Rectum_adenocarcinoma/g
s/AH/Rectum_adenocarcinoma/g
s/AJ/Uterine_Corpus_Endometrial_Carcinoma/g
s/AK/Kidney_renal_clear_cell_carcinoma/g
s/AL/Kidney_renal_papillary_cell_carcinoma/g
s/AM/Colon_adenocarcinoma/g
s/AN/Breast_invasive_carcinoma/g
s/AO/Breast_invasive_carcinoma/g
s/AP/Uterine_Corpus_Endometrial_Carcinoma/g
s/AQ/Breast_invasive_carcinoma/g
s/AR/Breast_invasive_carcinoma/g
s/AS/Kidney_renal_clear_cell_carcinoma/g
s/AT/Kidney_renal_papillary_cell_carcinoma/g
s/AU/Colon_adenocarcinoma/g
s/AV/Cell_Line_Control/g
s/AW/Uterine_Corpus_Endometrial_Carcinoma/g
s/AX/Uterine_Corpus_Endometrial_Carcinoma/g
s/AY/Colon_adenocarcinoma/g
s/AZ/Colon_adenocarcinoma/g
s/B0/Kidney_renal_clear_cell_carcinoma/g
s/B1/Kidney_renal_papillary_cell_carcinoma/g
s/B2/Kidney_renal_clear_cell_carcinoma/g
s/B3/Kidney_renal_papillary_cell_carcinoma/g
s/B4/Kidney_renal_clear_cell_carcinoma/g
s/B5/Uterine_Corpus_Endometrial_Carcinoma/g
s/B6/Breast_invasive_carcinoma/g
s/B7/Stomach_adenocarcinoma/g
s/B8/Kidney_renal_clear_cell_carcinoma/g
s/B9/Kidney_renal_papillary_cell_carcinoma/g
s/BA/Head_and_Neck_squamous_cell_carcinoma/g
s/BB/Head_and_Neck_squamous_cell_carcinoma/g
s/BC/Liver_hepatocellular_carcinoma/g
s/BD/Liver_hepatocellular_carcinoma/g
s/BF/Skin_Cutaneous_Melanoma/g
s/BG/Uterine_Corpus_Endometrial_Carcinoma/g
s/BH/Breast_invasive_carcinoma/g
s/BI/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/BJ/Thyroid_carcinoma/g
s/BK/Uterine_Corpus_Endometrial_Carcinoma/g
s/BL/Bladder_Urothelial_Carcinoma/g
s/BM/Rectum_adenocarcinoma/g
s/BP/Kidney_renal_clear_cell_carcinoma/g
s/BQ/Kidney_renal_papillary_cell_carcinoma/g
s/BR/Stomach_adenocarcinoma/g
s/BS/Uterine_Corpus_Endometrial_Carcinoma/g
s/BT/Bladder_Urothelial_Carcinoma/g
s/BW/Liver_hepatocellular_carcinoma/g
s/C4/Bladder_Urothelial_Carcinoma/g
s/C5/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/C8/Breast_invasive_carcinoma/g
s/C9/Head_and_Neck_squamous_cell_carcinoma/g
s/CA/Colon_adenocarcinoma/g
s/CB/Kidney_renal_clear_cell_carcinoma/g
s/CC/Liver_hepatocellular_carcinoma/g
s/CD/Stomach_adenocarcinoma/g
s/CE/Thyroid_carcinoma/g
s/CF/Bladder_Urothelial_Carcinoma/g
s/CG/Stomach_adenocarcinoma/g
s/CH/Prostate_adenocarcinoma/g
s/CI/Rectum_adenocarcinoma/g
s/CJ/Kidney_renal_clear_cell_carcinoma/g
s/CK/Colon_adenocarcinoma/g
s/CL/Rectum_adenocarcinoma/g
s/CM/Colon_adenocarcinoma/g
s/CN/Head_and_Neck_squamous_cell_carcinoma/g
s/CQ/Head_and_Neck_squamous_cell_carcinoma/g
s/CR/Head_and_Neck_squamous_cell_carcinoma/g
s/CS/Brain_Lower_Grade_Glioma/g
s/CU/Bladder_Urothelial_Carcinoma/g
s/CV/Head_and_Neck_squamous_cell_carcinoma/g
s/CW/Kidney_renal_clear_cell_carcinoma/g
s/CX/Head_and_Neck_squamous_cell_carcinoma/g
s/CZ/Kidney_renal_clear_cell_carcinoma/g
s/D1/Uterine_Corpus_Endometrial_Carcinoma/g
s/D3/Skin_Cutaneous_Melanoma/g
s/D5/Colon_adenocarcinoma/g
s/D6/Head_and_Neck_squamous_cell_carcinoma/g
s/D7/Stomach_adenocarcinoma/g
s/D8/Breast_invasive_carcinoma/g
s/D9/Skin_Cutaneous_Melanoma/g
s/DA/Skin_Cutaneous_Melanoma/g
s/DB/Brain_Lower_Grade_Glioma/g
s/DC/Rectum_adenocarcinoma/g
s/DD/Liver_hepatocellular_carcinoma/g
s/DE/Thyroid_carcinoma/g
s/DF/Uterine_Corpus_Endometrial_Carcinoma/g
s/DG/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/DH/Brain_Lower_Grade_Glioma/g
s/DI/Uterine_Corpus_Endometrial_Carcinoma/g
s/DJ/Thyroid_carcinoma/g
s/DK/Bladder_Urothelial_Carcinoma/g
s/DM/Colon_adenocarcinoma/g
s/DO/Thyroid_carcinoma/g
s/DQ/Head_and_Neck_squamous_cell_carcinoma/g
s/DR/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/DS/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/DT/Rectum_adenocarcinoma/g
s/DU/Brain_Lower_Grade_Glioma/g
s/DV/Kidney_renal_clear_cell_carcinoma/g
s/DW/Kidney_renal_papillary_cell_carcinoma/g
s/DX/Sarcoma/g
s/DY/Rectum_adenocarcinoma/g
s/DZ/Kidney_renal_papillary_cell_carcinoma/g
s/E1/Brain_Lower_Grade_Glioma/g
s/E2/Breast_invasive_carcinoma/g
s/E3/Thyroid_carcinoma/g
s/E5/Bladder_Urothelial_Carcinoma/g
s/E6/Uterine_Corpus_Endometrial_Carcinoma/g
s/E7/Bladder_Urothelial_Carcinoma/g
s/E8/Thyroid_carcinoma/g
s/E9/Breast_invasive_carcinoma/g
s/EA/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/EB/Skin_Cutaneous_Melanoma/g
s/EC/Uterine_Corpus_Endometrial_Carcinoma/g
s/ED/Liver_hepatocellular_carcinoma/g
s/EE/Skin_Cutaneous_Melanoma/g
s/EF/Rectum_adenocarcinoma/g
s/EI/Rectum_adenocarcinoma/g
s/EJ/Prostate_adenocarcinoma/g
s/EK/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/EL/Thyroid_carcinoma/g
s/EM/Thyroid_carcinoma/g
s/EO/Uterine_Corpus_Endometrial_Carcinoma/g
s/EP/Liver_hepatocellular_carcinoma/g
s/EQ/Stomach_adenocarcinoma/g
s/ER/Skin_Cutaneous_Melanoma/g
s/ES/Liver_hepatocellular_carcinoma/g
s/ET/Thyroid_carcinoma/g
s/EU/Kidney_renal_clear_cell_carcinoma/g
s/EV/Kidney_renal_papillary_cell_carcinoma/g
s/EW/Breast_invasive_carcinoma/g
s/EX/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/EY/Uterine_Corpus_Endometrial_Carcinoma/g
s/EZ/Brain_Lower_Grade_Glioma/g
s/F1/Stomach_adenocarcinoma/g
s/F2/Pancreatic_adenocarcinoma/g
s/F4/Colon_adenocarcinoma/g
s/F5/Rectum_adenocarcinoma/g
s/F6/Brain_Lower_Grade_Glioma/g
s/F7/Head_and_Neck_squamous_cell_carcinoma/g
s/F9/Kidney_renal_papillary_cell_carcinoma/g
s/FA/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/FB/Pancreatic_adenocarcinoma/g
s/FC/Prostate_adenocarcinoma/g
s/FD/Bladder_Urothelial_Carcinoma/g
s/FE/Thyroid_carcinoma/g
s/FF/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/FG/Brain_Lower_Grade_Glioma/g
s/FH/Thyroid_carcinoma/g
s/FI/Uterine_Corpus_Endometrial_Carcinoma/g
s/FJ/Bladder_Urothelial_Carcinoma/g
s/FK/Thyroid_carcinoma/g
s/FL/Uterine_Corpus_Endometrial_Carcinoma/g
s/FM/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/FN/Brain_Lower_Grade_Glioma/g
s/FP/Stomach_adenocarcinoma/g
s/FQ/Pancreatic_adenocarcinoma/g
s/FR/Skin_Cutaneous_Melanoma/g
s/FS/Skin_Cutaneous_Melanoma/g
s/FT/Bladder_Urothelial_Carcinoma/g
s/FU/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/FV/Liver_hepatocellular_carcinoma/g
s/FW/Skin_Cutaneous_Melanoma/g
s/FX/Sarcoma/g
s/FY/Thyroid_carcinoma/g
s/FZ/Pancreatic_adenocarcinoma/g
s/G2/Bladder_Urothelial_Carcinoma/g
s/G3/Liver_hepatocellular_carcinoma/g
s/G4/Colon_adenocarcinoma/g
s/G5/Rectum_adenocarcinoma/g
s/G6/Kidney_renal_clear_cell_carcinoma/g
s/G7/Kidney_renal_papillary_cell_carcinoma/g
s/G8/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/G9/Prostate_adenocarcinoma/g
s/GC/Bladder_Urothelial_Carcinoma/g
s/GD/Bladder_Urothelial_Carcinoma/g
s/GE/Thyroid_carcinoma/g
s/GF/Skin_Cutaneous_Melanoma/g
s/GG/Uterine_Corpus_Endometrial_Carcinoma/g
s/GH/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/GI/Breast_invasive_carcinoma/g
s/GJ/Liver_hepatocellular_carcinoma/g
s/GK/Kidney_renal_clear_cell_carcinoma/g
s/GL/Kidney_renal_papillary_cell_carcinoma/g
s/GM/Breast_invasive_carcinoma/g
s/GN/Skin_Cutaneous_Melanoma/g
s/GP/Acute_Myeloid_Leukemia/g
s/GR/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/GS/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/GU/Bladder_Urothelial_Carcinoma/g
s/GV/Bladder_Urothelial_Carcinoma/g
s/GZ/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/H1/Stomach_adenocarcinoma/g
s/H2/Thyroid_carcinoma/g
s/H3/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/H4/Bladder_Urothelial_Carcinoma/g
s/H5/Uterine_Corpus_Endometrial_Carcinoma/g
s/H6/Pancreatic_adenocarcinoma/g
s/H7/Head_and_Neck_squamous_cell_carcinoma/g
s/H8/Pancreatic_adenocarcinoma/g
s/H9/Prostate_adenocarcinoma/g
s/HA/Stomach_adenocarcinoma/g
s/HB/Sarcoma/g
s/HC/Prostate_adenocarcinoma/g
s/HD/Head_and_Neck_squamous_cell_carcinoma/g
s/HE/Kidney_renal_papillary_cell_carcinoma/g
s/HF/Stomach_adenocarcinoma/g
s/HG/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/HH/Stomach_adenocarcinoma/g
s/HI/Prostate_adenocarcinoma/g
s/HJ/Stomach_adenocarcinoma/g
s/HK/Brain_Lower_Grade_Glioma/g
s/HL/Head_and_Neck_squamous_cell_carcinoma/g
s/HM/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/HN/Breast_invasive_carcinoma/g
s/HP/Liver_hepatocellular_carcinoma/g
s/HQ/Bladder_Urothelial_Carcinoma/g
s/HR/Skin_Cutaneous_Melanoma/g
s/HS/Sarcoma/g
s/HT/Brain_Lower_Grade_Glioma/g
s/HU/Stomach_adenocarcinoma/g
s/HV/Pancreatic_adenocarcinoma/g
s/HW/Brain_Lower_Grade_Glioma/g
s/HZ/Pancreatic_adenocarcinoma/g
s/IA/Kidney_renal_papillary_cell_carcinoma/g
s/IB/Pancreatic_adenocarcinoma/g
s/IC/Esophageal_carcinoma/g
s/IE/Sarcoma/g
s/IF/Sarcoma/g
s/IG/Esophageal_carcinoma/g
s/IH/Skin_Cutaneous_Melanoma/g
s/IJ/Acute_Myeloid_Leukemia/g
s/IK/Brain_Lower_Grade_Glioma/g
s/IM/Thyroid_carcinoma/g
s/IN/Stomach_adenocarcinoma/g
s/IP/Stomach_adenocarcinoma/g
s/IQ/Head_and_Neck_squamous_cell_carcinoma/g
s/IR/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/IS/Sarcoma/g
s/IW/Sarcoma/g
s/IZ/Kidney_renal_papillary_cell_carcinoma/g
s/J1/Lung_squamous_cell_carcinoma/g
s/J2/Lung_adenocarcinoma/g
s/J4/Prostate_adenocarcinoma/g
s/J7/Kidney_renal_papillary_cell_carcinoma/g
s/J8/Thyroid_carcinoma/g
s/J9/Prostate_adenocarcinoma/g
s/JA/Head_and_Neck_squamous_cell_carcinoma/g
s/JL/Breast_invasive_carcinoma/g
s/JU/Uterine_Corpus_Endometrial_Carcinoma/g
s/JV/Sarcoma/g
s/JW/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/JX/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/JY/Esophageal_carcinoma/g
s/JZ/Esophageal_carcinoma/g
s/K1/Sarcoma/g
s/K4/Bladder_Urothelial_Carcinoma/g
s/K6/Uterine_Corpus_Endometrial_Carcinoma/g
s/K7/Liver_hepatocellular_carcinoma/g
s/K8/Skin_Cutaneous_Melanoma/g
s/KA/Esophageal_carcinoma/g
s/KB/Stomach_adenocarcinoma/g
s/KC/Prostate_adenocarcinoma/g
s/KD/Sarcoma/g
s/KE/Uterine_Corpus_Endometrial_Carcinoma/g
s/KF/Sarcoma/g
s/KG/Pancreatic_adenocarcinoma/g
s/KH/Esophageal_carcinoma/g
s/KJ/Uterine_Corpus_Endometrial_Carcinoma/g
s/KK/Prostate_adenocarcinoma/g
s/KL/Kidney_Chromophobe/g
s/KM/Kidney_Chromophobe/g
s/KN/Kidney_Chromophobe/g
s/KO/Kidney_Chromophobe/g
s/KP/Uterine_Corpus_Endometrial_Carcinoma/g
s/KQ/Bladder_Urothelial_Carcinoma/g
s/KR/Liver_hepatocellular_carcinoma/g
s/KS/Thyroid_carcinoma/g
s/KT/Brain_Lower_Grade_Glioma/g
s/KU/Head_and_Neck_squamous_cell_carcinoma/g
s/KV/Kidney_renal_papillary_cell_carcinoma/g
s/KZ/Stomach_adenocarcinoma/g
s/L1/Pancreatic_adenocarcinoma/g
s/L3/Lung_squamous_cell_carcinoma/g
s/L4/Lung_adenocarcinoma/g
s/L5/Esophageal_carcinoma/g
s/L6/Thyroid_carcinoma/g
s/L7/Esophageal_carcinoma/g
s/L8/Kidney_renal_papillary_cell_carcinoma/g
s/L9/Lung_adenocarcinoma/g
s/LA/Lung_squamous_cell_carcinoma/g
s/LB/Pancreatic_adenocarcinoma/g
s/LC/Bladder_Urothelial_Carcinoma/g
s/LD/Breast_invasive_carcinoma/g
s/LG/Liver_hepatocellular_carcinoma/g
s/LH/Skin_Cutaneous_Melanoma/g
s/LI/Sarcoma/g
s/LK/Mesothelioma/g
s/LL/Breast_invasive_carcinoma/g
s/LN/Esophageal_carcinoma/g
s/LP/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/LQ/Breast_invasive_carcinoma/g
s/LS/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/LT/Bladder_Urothelial_Carcinoma/g
s/M7/Prostate_adenocarcinoma/g
s/M8/Pancreatic_adenocarcinoma/g
s/M9/Esophageal_carcinoma/g
s/MA/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/MB/Sarcoma/g
s/ME/Lung_adenocarcinoma/g
s/MF/Lung_squamous_cell_carcinoma/g
s/MG/Prostate_adenocarcinoma/g
s/MH/Kidney_renal_papillary_cell_carcinoma/g
s/MI/Liver_hepatocellular_carcinoma/g
s/MJ/Sarcoma/g
s/MK/Thyroid_carcinoma/g
s/ML/Lung_squamous_cell_carcinoma/g
s/MM/Kidney_renal_clear_cell_carcinoma/g
s/MN/Lung_adenocarcinoma/g
s/MO/Sarcoma/g
s/MP/Lung_adenocarcinoma/g
s/MQ/Mesothelioma/g
s/MR/Liver_hepatocellular_carcinoma/g
s/MS/Breast_invasive_carcinoma/g
s/MT/Head_and_Neck_squamous_cell_carcinoma/g
s/MU/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/MV/Bladder_Urothelial_Carcinoma/g
s/MW/Kidney_renal_clear_cell_carcinoma/g
s/MX/Stomach_adenocarcinoma/g
s/MY/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/MZ/Head_and_Neck_squamous_cell_carcinoma/g
s/N1/Sarcoma/g
s/N5/Uterine_Carcinosarcoma/g
s/N6/Uterine_Carcinosarcoma/g
s/N7/Uterine_Carcinosarcoma/g
s/N8/Uterine_Carcinosarcoma/g
s/N9/Uterine_Carcinosarcoma/g
s/NA/Uterine_Carcinosarcoma/g
s/NB/Lung_adenocarcinoma/g
s/NC/Lung_squamous_cell_carcinoma/g
s/ND/Uterine_Carcinosarcoma/g
s/NF/Uterine_Carcinosarcoma/g
s/NG/Uterine_Carcinosarcoma/g
s/NH/Colon_adenocarcinoma/g
s/NI/Liver_hepatocellular_carcinoma/g
s/NJ/Lung_adenocarcinoma/g
s/NK/Lung_squamous_cell_carcinoma/g
s/NM/Head_and_Neck_squamous_cell_carcinoma/g
s/NP/Kidney_Chromophobe/g
s/NQ/Mesothelioma/g
s/NS/Skin_Cutaneous_Melanoma/g
s/O1/Lung_adenocarcinoma/g
s/O2/Lung_squamous_cell_carcinoma/g
s/O8/Liver_hepatocellular_carcinoma/g
s/O9/Kidney_renal_papillary_cell_carcinoma/g
s/OC/Lung_squamous_cell_carcinoma/g
s/OD/Skin_Cutaneous_Melanoma/g
s/OE/Pancreatic_adenocarcinoma/g
s/OJ/Thyroid_carcinoma/g
s/OK/Breast_invasive_carcinoma/g
s/OL/Breast_invasive_carcinoma/g
s/OR/Adrenocortical_carcinoma/g
s/OU/Adrenocortical_carcinoma/g
s/OW/Miscellaneous/g
s/OX/Glioblastoma_multiforme/g
s/OY/Ovarian_serous_cystadenocarcinoma/g
s/P3/Head_and_Neck_squamous_cell_carcinoma/g
s/P4/Kidney_renal_papillary_cell_carcinoma/g
s/P5/Brain_Lower_Grade_Glioma/g
s/P6/Adrenocortical_carcinoma/g
s/P7/Pheochromocytoma_and_Paraganglioma/g
s/P8/Pheochromocytoma_and_Paraganglioma/g
s/P9/Pancreatic_adenocarcinoma/g
s/PA/Adrenocortical_carcinoma/g
s/PB/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/PC/Sarcoma/g
s/PD/Liver_hepatocellular_carcinoma/g
s/PE/Breast_invasive_carcinoma/g
s/PG/Uterine_Corpus_Endometrial_Carcinoma/g
s/PH/Acute_Myeloid_Leukemia/g
s/PJ/Kidney_renal_papillary_cell_carcinoma/g
s/PK/Adrenocortical_carcinoma/g
s/PL/Breast_invasive_carcinoma/g
s/PN/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/PQ/Bladder_Urothelial_Carcinoma/g
s/PR/Pheochromocytoma_and_Paraganglioma/g
s/PT/Sarcoma/g
s/PZ/Pancreatic_adenocarcinoma/g
s/Q1/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/Q2/Kidney_renal_papillary_cell_carcinoma/g
s/Q3/Pancreatic_adenocarcinoma/g
s/Q4/Acute_Myeloid_Leukemia/g
s/Q9/Esophageal_carcinoma/g
s/QA/Liver_hepatocellular_carcinoma/g
s/QB/Skin_Cutaneous_Melanoma/g
s/QC/Sarcoma/g
s/QD/Thyroid_carcinoma/g
s/QF/Uterine_Corpus_Endometrial_Carcinoma/g
s/QG/Colon_adenocarcinoma/g
s/QH/Brain_Lower_Grade_Glioma/g
s/QJ/Ovarian_serous_cystadenocarcinoma/g
s/QK/Head_and_Neck_squamous_cell_carcinoma/g
s/QL/Colon_adenocarcinoma/g
s/QM/Uterine_Carcinosarcoma/g
s/QN/Uterine_Carcinosarcoma/g
s/QQ/Sarcoma/g
s/QR/Pheochromocytoma_and_Paraganglioma/g
s/QS/Uterine_Corpus_Endometrial_Carcinoma/g
s/QT/Pheochromocytoma_and_Paraganglioma/g
s/QU/Prostate_adenocarcinoma/g
s/QV/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/QW/Stomach_adenocarcinoma/g
s/R1/Colon_adenocarcinoma/g
s/R2/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/R3/Bladder_Urothelial_Carcinoma/g
s/R5/Stomach_adenocarcinoma/g
s/R6/Esophageal_carcinoma/g
s/R7/Head_and_Neck_squamous_cell_carcinoma/g
s/R8/Brain_Lower_Grade_Glioma/g
s/R9/Ovarian_serous_cystadenocarcinoma/g
s/RA/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/RB/Pancreatic_adenocarcinoma/g
s/RC/Liver_hepatocellular_carcinoma/g
s/RD/Stomach_adenocarcinoma/g
s/RE/Esophageal_carcinoma/g
s/RG/Liver_hepatocellular_carcinoma/g
s/RH/Head_and_Neck_squamous_cell_carcinoma/g
s/RL/Pancreatic_adenocarcinoma/g
s/RM/Pheochromocytoma_and_Paraganglioma/g
s/RN/Sarcoma/g
s/RP/Skin_Cutaneous_Melanoma/g
s/RQ/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/RR/Glioblastoma_multiforme/g
s/RS/Head_and_Neck_squamous_cell_carcinoma/g
s/RT/Pheochromocytoma_and_Paraganglioma/g
s/RU/Colon_adenocarcinoma/g
s/RV/Pancreatic_adenocarcinoma/g
s/RW/Pheochromocytoma_and_Paraganglioma/g
s/RX/Pheochromocytoma_and_Paraganglioma/g
s/RY/Brain_Lower_Grade_Glioma/g
s/RZ/Uveal_Melanoma/g
s/S2/Lung_adenocarcinoma/g
s/S3/Breast_invasive_carcinoma/g
s/S4/Pancreatic_adenocarcinoma/g
s/S5/Bladder_Urothelial_Carcinoma/g
s/S6/Testicular_Germ_Cell_Tumors/g
s/S7/Pheochromocytoma_and_Paraganglioma/g
s/S8/Esophageal_carcinoma/g
s/S9/Brain_Lower_Grade_Glioma/g
s/SA/Pheochromocytoma_and_Paraganglioma/g
s/SB/Testicular_Germ_Cell_Tumors/g
s/SC/Mesothelioma/g
s/SD/Pancreatic_adenocarcinoma/g
s/SE/Pheochromocytoma_and_Paraganglioma/g
s/SG/Sarcoma/g
s/SH/Mesothelioma/g
s/SI/Sarcoma/g
s/SJ/Uterine_Corpus_Endometrial_Carcinoma/g
s/SK/Colon_adenocarcinoma/g
s/SL/Uterine_Corpus_Endometrial_Carcinoma/g
s/SN/Testicular_Germ_Cell_Tumors/g
s/SO/Testicular_Germ_Cell_Tumors/g
s/SP/Pheochromocytoma_and_Paraganglioma/g
s/SQ/Pheochromocytoma_and_Paraganglioma/g
s/SR/Pheochromocytoma_and_Paraganglioma/g
s/SS/Colon_adenocarcinoma/g
s/ST/Head_and_Neck_squamous_cell_carcinoma/g
s/SU/Prostate_adenocarcinoma/g
s/SW/Stomach_adenocarcinoma/g
s/SX/Kidney_renal_papillary_cell_carcinoma/g
s/SY/Bladder_Urothelial_Carcinoma/g
s/T1/Liver_hepatocellular_carcinoma/g
s/T2/Head_and_Neck_squamous_cell_carcinoma/g
s/T3/Head_and_Neck_squamous_cell_carcinoma/g
s/T6/Lung_adenocarcinoma/g
s/T7/Kidney_renal_clear_cell_carcinoma/g
s/T9/Colon_adenocarcinoma/g
s/TE/Skin_Cutaneous_Melanoma/g
s/TG/Head_and_Neck_squamous_cell_carcinoma/g
s/TK/Prostate_adenocarcinoma/g
s/TL/Stomach_adenocarcinoma/g
s/TM/Brain_Lower_Grade_Glioma/g
s/TN/Head_and_Neck_squamous_cell_carcinoma/g
s/TP/Prostate_adenocarcinoma/g
s/TQ/Brain_Lower_Grade_Glioma/g
s/TR/Skin_Cutaneous_Melanoma/g
s/TS/Mesothelioma/g
s/TT/Pheochromocytoma_and_Paraganglioma/g
s/TV/Breast_invasive_carcinoma/g
s/UB/Liver_hepatocellular_carcinoma/g
s/UC/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/UD/Mesothelioma/g
s/UE/Sarcoma/g
s/UF/Head_and_Neck_squamous_cell_carcinoma/g
s/UJ/Lung_squamous_cell_carcinoma/g
s/UL/Breast_invasive_carcinoma/g
s/UN/Kidney_renal_papillary_cell_carcinoma/g
s/UP/Head_and_Neck_squamous_cell_carcinoma/g
s/UR/Prostate_adenocarcinoma/g
s/US/Pancreatic_adenocarcinoma/g
s/UT/Mesothelioma/g
s/UU/Breast_invasive_carcinoma/g
s/UV/Liver_hepatocellular_carcinoma/g
s/UW/Kidney_Chromophobe/g
s/UY/Bladder_Urothelial_Carcinoma/g
s/UZ/Kidney_renal_papillary_cell_carcinoma/g
s/V1/Prostate_adenocarcinoma/g
s/V2/Prostate_adenocarcinoma/g
s/V3/Uveal_Melanoma/g
s/V4/Uveal_Melanoma/g
s/V5/Esophageal_carcinoma/g
s/V6/Stomach_adenocarcinoma/g
s/V7/Breast_invasive_carcinoma/g
s/V8/Kidney_renal_clear_cell_carcinoma/g
s/V9/Kidney_renal_papillary_cell_carcinoma/g
s/VA/Stomach_adenocarcinoma/g
s/VB/Lymphoid_Neoplasm_Diffuse_Large_Bcell_Lymphoma/g
s/VD/Uveal_Melanoma/g
s/VF/Testicular_Germ_Cell_Tumors/g
s/VG/Ovarian_serous_cystadenocarcinoma/g
s/VK/Colon_adenocarcinoma/g
s/VL/Rectum_adenocarcinoma/g
s/VM/Brain_Lower_Grade_Glioma/g
s/VN/Prostate_adenocarcinoma/g
s/VP/Prostate_adenocarcinoma/g
s/VQ/Stomach_adenocarcinoma/g
s/VR/Esophageal_carcinoma/g
s/VS/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/VT/Sarcoma/g
s/VV/Brain_Lower_Grade_Glioma/g
s/VW/Brain_Lower_Grade_Glioma/g
s/VX/Stomach_adenocarcinoma/g
s/VZ/Pheochromocytoma_and_Paraganglioma/g
s/W2/Pheochromocytoma_and_Paraganglioma/g
s/W3/Skin_Cutaneous_Melanoma/g
s/W4/Testicular_Germ_Cell_Tumors/g
s/W5/Cholangiocarcinoma/g
s/W6/Cholangiocarcinoma/g
s/W7/Cholangiocarcinoma/g
s/W8/Breast_invasive_carcinoma/g
s/W9/Brain_Lower_Grade_Glioma/g
s/WA/Head_and_Neck_squamous_cell_carcinoma/g
s/WB/Pheochromocytoma_and_Paraganglioma/g
s/WC/Uveal_Melanoma/g
s/WD/Cholangiocarcinoma/g
s/WE/Skin_Cutaneous_Melanoma/g
s/WF/Pancreatic_adenocarcinoma/g
s/WG/Lung_squamous_cell_carcinoma/g
s/WH/Brain_Lower_Grade_Glioma/g
s/WJ/Liver_hepatocellular_carcinoma/g
s/WK/Sarcoma/g
s/WL/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/WM/Kidney_renal_clear_cell_carcinoma/g
s/WN/Kidney_renal_papillary_cell_carcinoma/g
s/WP/Sarcoma/g
s/WQ/Liver_hepatocellular_carcinoma/g
s/WR/Ovarian_serous_cystadenocarcinoma/g
s/WS/Colon_adenocarcinoma/g
s/WT/Breast_invasive_carcinoma/g
s/WU/Colon_adenocarcinoma/g
s/WW/Prostate_adenocarcinoma/g
s/WX/Liver_hepatocellular_carcinoma/g
s/WY/Brain_Lower_Grade_Glioma/g
s/WZ/Testicular_Germ_Cell_Tumors/g
s/X2/Sarcoma/g
s/X3/Testicular_Germ_Cell_Tumors/g
s/X4/Prostate_adenocarcinoma/g
s/X5/Bladder_Urothelial_Carcinoma/g
s/X6/Sarcoma/g
s/X7/Thymoma/g
s/X8/Esophageal_carcinoma/g
s/X9/Sarcoma/g
s/XA/Prostate_adenocarcinoma/g
s/XB/Esophageal_carcinoma/g
s/XC/Lung_squamous_cell_carcinoma/g
s/XD/Pancreatic_adenocarcinoma/g
s/XE/Testicular_Germ_Cell_Tumors/g
s/XF/Bladder_Urothelial_Carcinoma/g
s/XG/Pheochromocytoma_and_Paraganglioma/g
s/XH/Thymoma/g
s/XJ/Prostate_adenocarcinoma/g
s/XK/Prostate_adenocarcinoma/g
s/XM/Thymoma/g
s/XN/Pancreatic_adenocarcinoma/g
s/XP/Esophageal_carcinoma/g
s/XQ/Prostate_adenocarcinoma/g
s/XR/Liver_hepatocellular_carcinoma/g
s/XS/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/XT/Mesothelioma/g
s/XU/Thymoma/g
s/XV/Skin_Cutaneous_Melanoma/g
s/XX/Breast_invasive_carcinoma/g
s/XY/Testicular_Germ_Cell_Tumors/g
s/Y3/Acute_Myeloid_Leukemia/g
s/Y5/Sarcoma/g
s/Y6/Prostate_adenocarcinoma/g
s/Y8/Kidney_renal_papillary_cell_carcinoma/g
s/YA/Liver_hepatocellular_carcinoma/g
s/YB/Pancreatic_adenocarcinoma/g
s/YC/Bladder_Urothelial_Carcinoma/g
s/YD/Skin_Cutaneous_Melanoma/g
s/YF/Bladder_Urothelial_Carcinoma/g
s/YG/Skin_Cutaneous_Melanoma/g
s/YH/Pancreatic_adenocarcinoma/g
s/YJ/Prostate_adenocarcinoma/g
s/YL/Prostate_adenocarcinoma/g
s/YN/Skin_Cutaneous_Melanoma/g
s/YR/Cholangiocarcinoma/g
s/YS/Mesothelioma/g
s/YT/Thymoma/g
s/YU/Testicular_Germ_Cell_Tumors/g
s/YV/Uveal_Melanoma/g
s/YW/Sarcoma/g
s/YX/Stomach_adenocarcinoma/g
s/YY/Pancreatic_adenocarcinoma/g
s/YZ/Uveal_Melanoma/g
s/Z2/Skin_Cutaneous_Melanoma/g
s/Z3/Sarcoma/g
s/Z4/Sarcoma/g
s/Z5/Pancreatic_adenocarcinoma/g
s/Z6/Esophageal_carcinoma/g
s/Z7/Breast_invasive_carcinoma/g
s/Z8/Pancreatic_adenocarcinoma/g
s/ZA/Stomach_adenocarcinoma/g
s/ZB/Thymoma/g
s/ZC/Thymoma/g
s/ZD/Cholangiocarcinoma/g
s/ZE/Lung_squamous_cell_carcinoma/g
s/ZF/Bladder_Urothelial_Carcinoma/g
s/ZG/Prostate_adenocarcinoma/g
s/ZH/Cholangiocarcinoma/g
s/ZJ/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
s/ZK/Cholangiocarcinoma/g
s/ZL/Thymoma/g
s/ZM/Testicular_Germ_Cell_Tumors/g
s/ZN/Mesothelioma/g
s/ZP/Liver_hepatocellular_carcinoma/g
s/ZQ/Stomach_adenocarcinoma/g
s/ZR/Esophageal_carcinoma/g
s/ZS/Liver_hepatocellular_carcinoma/g
s/ZT/Thymoma/g
s/ZU/Cholangiocarcinoma/g
s/ZW/Pancreatic_adenocarcinoma/g
s/ZX/Cervical_squamous_cell_carcinoma_and_endocervical_adenocarcinoma/g
